// <auto-generated />
using System;
using AutoCatch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoCatch.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416080835_UpdatePttReplies")]
    partial class UpdatePttReplies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("AutoCatch.Models.PttSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoardConfigs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RefreshIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PttSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardConfigs = "[{\"Name\":\"Lifeismoney\",\"NumPost\":10,\"MinNrec\":0,\"HideReplies\":true}]",
                            Enabled = true,
                            RefreshIntervalMinutes = 30
                        });
                });

            modelBuilder.Entity("AutoCatch.Models.SocialPost", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("AutoCatch.Models.ThreadsSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinLikes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumPost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RefreshIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ThreadsSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Enabled = true,
                            Keywords = "[\"AI\"]",
                            MinLikes = 0,
                            NumPost = 10,
                            RefreshIntervalMinutes = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
